-- MySQL Script generated by MySQL Workbench
-- 04/22/16 18:55:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema individuals
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `individuals` ;

-- -----------------------------------------------------
-- Schema individuals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `individuals` DEFAULT CHARACTER SET utf8 ;
USE `individuals` ;

-- -----------------------------------------------------
-- Table `individuals`.`info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`info` ;

CREATE TABLE IF NOT EXISTS `individuals`.`info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lastNm` TEXT NOT NULL,
  `firstNm` TEXT NOT NULL,
  `midNm` TEXT NULL DEFAULT NULL,
  `indvlPK` INT(11) NOT NULL,
  `actvAGReg` BIT(1) NOT NULL,
  `link` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`crntemps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`crntemps` ;

CREATE TABLE IF NOT EXISTS `individuals`.`crntemps` (
  `info_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `orgNm` TEXT NULL,
  `orgPK` INT(11) NULL,
  `str1` TEXT NULL DEFAULT NULL,
  `str2` TEXT NULL,
  `city` TEXT NULL,
  `state` TEXT NULL,
  `cntry` TEXT NULL,
  `postlCd` TEXT NULL,
  PRIMARY KEY (`id`, `info_id`),
  CONSTRAINT `fk_crntemps_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`brnchoflocs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`brnchoflocs` ;

CREATE TABLE IF NOT EXISTS `individuals`.`brnchoflocs` (
  `info_id` INT(11) NOT NULL,
  `crntemps_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `str1` TEXT NULL,
  `city` TEXT NULL,
  `state` TEXT NULL,
  `cntry` TEXT NULL,
  `postlCd` TEXT NULL,
  PRIMARY KEY (`id`, `info_id`, `crntemps_id`),
  INDEX `fk_brnchoflocs_crntemps1_idx` (`crntemps_id` ASC),
  CONSTRAINT `fk_brnchoflocs_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brnchoflocs_crntemps1`
    FOREIGN KEY (`crntemps_id`)
    REFERENCES `individuals`.`crntemps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`crntrgstns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`crntrgstns` ;

CREATE TABLE IF NOT EXISTS `individuals`.`crntrgstns` (
  `info_id` INT(11) NOT NULL,
  `crntemps_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `regAuth` TEXT NULL DEFAULT NULL,
  `regCat` TEXT NULL DEFAULT NULL,
  `st` TEXT NULL DEFAULT NULL,
  `stDt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`,`info_id`, `crntemps_id`),
  INDEX `fk_crntrgstns_crntemps1_idx` (`crntemps_id` ASC),
  CONSTRAINT `fk_crntrgstns_info1`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crntrgstns_crntemps1`
    FOREIGN KEY (`crntemps_id`)
    REFERENCES `individuals`.`crntemps` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`drps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`drps` ;

CREATE TABLE IF NOT EXISTS `individuals`.`drps` (
  `info_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `hasRegAction` BIT(1) NULL DEFAULT NULL,
  `hasCriminal` BIT(1) NULL DEFAULT NULL,
  `hasBankrupt` BIT(1) NULL DEFAULT NULL,
  `hasCivilJudc` BIT(1) NULL DEFAULT NULL,
  `hasBond` BIT(1) NULL DEFAULT NULL,
  `hasJudgment` BIT(1) NULL DEFAULT NULL,
  `hasInvstgn` BIT(1) NULL DEFAULT NULL,
  `hasCustComp` BIT(1) NULL DEFAULT NULL,
  `hasTermination` BIT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `info_id`),
  CONSTRAINT `fk_drps_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`dsgntns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`dsgntns` ;

CREATE TABLE IF NOT EXISTS `individuals`.`dsgntns` (
  `info_id` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dsgntnNm` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`,`info_id`),
  CONSTRAINT `fk_dsgntns_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`emphss`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`emphss` ;

CREATE TABLE IF NOT EXISTS `individuals`.`emphss` (
  `info_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `fromDt` DATE NULL DEFAULT NULL,
  `orgNm` TEXT NULL DEFAULT NULL,
  `city` TEXT NULL DEFAULT NULL,
  `state` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`,`info_id`),
  CONSTRAINT `fk_emphss_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`exms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`exms` ;

CREATE TABLE IF NOT EXISTS `individuals`.`exms` (
  `info_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `exmCd` TEXT NULL,
  `exmNm` TEXT NULL DEFAULT NULL,
  `exmDt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`,`info_id`),
  CONSTRAINT `fk_exms_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`othrbuss`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`othrbuss` ;

CREATE TABLE IF NOT EXISTS `individuals`.`othrbuss` (
  `info_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`,`info_id`),
  CONSTRAINT `fk_othrbuss_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `individuals`.`othrnms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`othrnms` ;

CREATE TABLE IF NOT EXISTS `individuals`.`othrnms` (
  `info_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastNm` TEXT NULL DEFAULT NULL,
  `firstNm` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`,`info_id`),
  CONSTRAINT `fk_othrnms_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------othrnms------------------------------------
-- Table `individuals`.`prevrgstns`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `individuals`.`prevrgstns` ;

CREATE TABLE IF NOT EXISTS `individuals`.`prevrgstns` (
  `info_id` INT(11) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `orgNm` TEXT NULL DEFAULT NULL,
  `orgPK` INT(11) NULL DEFAULT NULL,
  `regBeginDt` DATE NULL DEFAULT NULL,
  `regEndDt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`,`info_id`),
  CONSTRAINT `fk_prevrgstns_info`
    FOREIGN KEY (`info_id`)
    REFERENCES `individuals`.`info` (`id`)
    ON DELETE cascade
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
